### PR TITLE
import fixes and improvements

### PR DESCRIPTION
**Pull request by duckworth**
- Fixed import assumed codeDisplay always present.
- Fixed replace any occurrence of sha string instead of only in param.
- Use name if issuer is not present.
- Add logger warning to output to stderr for Alfred debugging.
- Add import file into workflow configuration and 'ente import' alfred command to run the import.
- Make username in subtitle and username in title configurable option in the workflow (useful when you have many totp from the same Issuer).
- Added github action to auto release workflow on push of tag matching v*

### CODE REVIEW

**Comment by chkpwd** [comment]
@duckworth I appreciate the work put into this. I'll review and merge tonight if no issues found. Fair warning, I'm starting development of the Raycast extension as well. Due to this, I'm no longer running Alfred in my environment.

**Review by chkpwd — APPROVED** [review]
LGTM 🎊

**Comment by duckworth** [comment]
@chkpwd thanks for getting this started I have been meaning to fix up a workflow I had started but this works out better. Mine has support for reading the existing ente encrypted export but the decryption takes too long to use as part of the workflow. I would like to add support for secure storage in this workflow though.

**Comment by duckworth** [comment]
I would also suggest separating out each workflow into it's own repo as that caused some friction.

**Pull request merged**
